[Appearance]
color_scheme_path=/home/k0oda/.local/share/color-schemes/DankMatugen.colors
custom_palette=true
icon_theme=WhiteSur-light
standard_dialogs=xdgdesktopportal

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\t\xf3\0\0\x5i\0\0\0\0\0\0\0\0\0\0\t\xff\0\0\x5\x9f\0\0\0\0\x2\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\t\xf3\0\0\x5i)
