[Appearance]
color_scheme_path=/home/k0oda/.local/share/color-schemes/DankMatugen.colors
custom_palette=true
icon_theme=WhiteSur

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\xf9\0\0\x5k\0\0\0\0\0\0\0\0\0\0\x4\xf9\0\0\x5k\0\0\0\0\0\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\x4\xf9\0\0\x5k)
