-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "desc:Dell Inc. DELL U2518D 3C4YP99HARBL", mode = "2560x1440@59.951", position = "0x0", scale = 1, vrr = 0 })
