cursor #e3e1e9
cursor_text_color #c6c6d0

foreground            #e3e1e9
background            #121318
selection_foreground  #2b3042
selection_background  #c1c5dd
url_color             #b5c4ff

color0   #121318
color1   #ff7297
color2   #7fff94
color3   #fff972
color4   #9daef2
color5   #344479
color6   #b5c4ff
color7   #eff3ff
color8   #404249
color9   #ff9fb8
color10  #a5ffb4
color11  #fffba5
color12  #c0ccff
color13  #cbd5ff
color14  #dde4ff
color15  #f8faff
